universidades = [
    # Acre
    "Universidade Federal do Acre",
    "IFAC - Instituto Federal do Acre",
    "UFAC - Universidade Federal do Acre",
    "FADISI - Faculdade Diocesana São José",
    "UNAMA - Universidade da Amazônia",
    "UNESA - Universidade Estácio de Sá",
    "UNINTER - Grupo Educacional Uninter",
    
    # Alagoas
    "UNEAL - Universidade Estadual de Alagoas",
    "UNCIASAL - Universidade Estadual de Ciências da Saúde de Alagoas",
    "IFAL - Instituto Federal de Alagoas",
    "UFAL - Universidade Federal de Alagoas",
    "CESMAC - Centro de Estudos Superiores de Maceió",
    "FAP - Faculdade Pitágoras",
    "FITS - Faculdade Integrada Tiradentes",
    
    # Amapá
    "UEAP - Universidade Estadual do Amapá",
    "IFAP - Instituto Federal do Amapá",
    "UNIFAP - Universidade Federal do Amapá",
    "CEAP - Centro de Ensino Superior do Amapá",
    
    # Amazonas
    "UEA - Universidade do Estado do Amazonas",
    "IFAM - Instituto Federal do Amazonas",
    "UFAM - Universidade Federal do Amazonas",
    "INPA - Instituto Nacional de Pesquisas da Amazônia",
    "ULBRA - Universidade Luterana do Brasil",
    "UNINILTONLINS - Universidade Nilton Lins",
    "Fametro - Faculdade Metropolitana de Manaus",
    "Uninorte - Centro Universitário do Norte",
    "Unip - Universidade Paulista",
    
    # Ceará
    "UECE - Universidade Estadual do Ceará",
    "URCA - Universidade Regional do Cariri",
    "UVA - Universidade Estadual Vale do Acaraú",
    "IFCE - Instituto Federal do Ceará",
    "UFC - Universidade Federal do Ceará",
    "UNILAB - Universidade Federal de Integração Luso-Afro-Brasileira",
    "UFCA - Universidade Federal do Cariri",
    "FCC - Faculdade Católica do Ceará",
    "FCF - Faculdade Católica de Fortaleza",
    "FCRS - Faculdade Católica Rainha do Sertão",
    "UNICHRISTUS - Centro Universitário Christus",
    "UNIFAMETRO - Centro Universitário Fametro",
    "UNIFOR - Universidade de Fortaleza",
    "UNICATÓLICA - Centro Universitário Católica de Quixadá",
    "FA7 - Faculdade 7 de Setembro",
    "FFB - Faculdade Farias Brito",
    "FLF - Faculdade Luciano Feijão",
    "Unifametro - Centro Universitário Fametro",
    
    # Distrito Federal
    "UnDF - Universidade do Distrito Federal Jorge Amaury",
    "IFB - Instituto Federal de Brasília",
    "UnB - Universidade de Brasília",
    "ENAP - Escola Nacional de Administração Pública",
    "UCB - Universidade Católica de Brasília",
    "SENAI - Serviço Nacional de Aprendizagem Industrial",
    "CEUB - Centro Universitário de Brasília",
    "FACITEC - Faculdade de Ciências Sociais e Tecnológicas",
    "FTB - Faculdades Integradas da Terra de Brasília",
    "IESB - Instituto de Educação Superior de Brasília",
    "SENAC - Faculdade Senac - Distrito Federal",
    "UNIEURO - Centro Universitário Euroamericano",
    "UNIP - Universidade Paulista",
    "UNOPAR - Universidade Norte do Paraná",
    "FAPRO - Faculdade Projeção",
    
    # Espírito Santo
    "FACELI - Faculdade de Ensino Superior de Linhares",
    "UnAC - Universidade Aberta Capixaba",
    "IFES - Instituto Federal do Espírito Santo",
    "UFES - Universidade Federal do Espírito Santo",
    "EMESCAM - Escola Superior de Ciências da Santa Casa de Misericórdia de Vitória",
    "CUSC - Centro Universitário São Camilo",
    "UVV - Universidade Vila Velha",
    "DOCTUM - Rede de Ensino Doctum",
    "FDV - Faculdades Integradas de Vitória",
    "FUCAPE - FUCAPE Business School",
    "UNESA - Universidade Estácio de Sá",
    
    # Goiás
    "UniRV (FESURV) - Universidade de Rio Verde",
    "UEG - Universidade Estadual de Goiás",
    "UFJ - Universidade Federal de Jataí",
    "UFCAT - Universidade Federal de Catalão",
    "IFG - Instituto Federal de Goiás",
    "UFG - Universidade Federal de Goiás",
    "IF Goiano - Instituto Federal Goiano",
    "UniEVANGÉLICA - Universidade Evangélica de Goiás",
    "PUC - Pontifícia Universidade Católica de Goiás",
    "UNIVERSO - Universidade Salgado de Oliveira",
    "ULBRA - Universidade Luterana do Brasil",
    "ALFA - Faculdade Alves Faria",
    "FACEG - Faculdade Evangelica de Goianesia",
    "UNESA - Universidade Estácio de Sá",
    "UNIP - Universidade Paulista",
    "UNIFASC - Faculdade Unifasc",
    "IAESUP - Faculdades e Colégio Aphonsiano",
    
    # Maranhão
    "UEMA - Universidade Estadual do Maranhão",
    "UEMASUL - Universidade Estadual da Região Tocantina do Maranhão",
    "IEMA - Instituto Estadual do Maranhão",
    "IFMA - Instituto Federal do Maranhão",
    "UFMA - Universidade Federal do Maranhão",
    "CEST - Faculdade Santa Terezinha",
    "FACIMP - Faculdade de Imperatriz",
    
    # Mato Grosso
    "UNEMAT - Universidade do Estado de Mato Grosso",
    "IFMT - Instituto Federal do Mato Grosso",
    "UFMT - Universidade Federal de Mato Grosso",
    "UFR - Universidade Federal de Rondonópolis",
    "UNIC (UNIME) - Universidade de Cuiabá",
    "IPE - Instituto Parecis de Ensino, Desenvolvimento e Pesquisa",
    
    # Mato Grosso do Sul
    "UEMS - Universidade Estadual do Mato Grosso do Sul",
    "UFGD - Universidade Federal da Grande Dourados",
    "IFMS - Instituto Federal de Mato Grosso do Sul",
    "UFMS - Universidade Federal do Mato Grosso do Sul",
    "UCDB - Universidade Católica Dom Bosco",
    "Uniderp - Universidade Anhanguera",
    "UNIGRAN - Centro Universitário da Grande Dourados",
    
    # Minas Gerais
    "FJP - Fundação João Pinheiro",
    "UEMG - Universidade do Estado de Minas Gerais",
    "UNIMONTES - Universidade Estadual de Montes Claros",
    "CEFET-MG - Centro Federal de Educação Tecnológica de Minas Gerais",
    "IFMG - Instituto Federal de Minas Gerais",
    "IFNMG - Instituto Federal do Norte de Minas Gerais",
    "IFSUDESTEMG - Instituto Federal do Sudeste de Minas",
    "IFSULDEMINAS - Instituto Federal do Sul de Minas",
    "IFTM - Instituto Federal do Triângulo Mineiro",
    "UFJF - Universidade Federal de Juiz de Fora",
    "UFLA - Universidade Federal de Lavras",
    "UFMG - Universidade Federal de Minas Gerais",
    "UFOP - Universidade Federal de Ouro Preto",
    "UFSJ - Universidade Federal de São João del-Rei",
    "UFTM - Universidade Federal do Triângulo Mineiro",
    "UFU - Universidade Federal de Uberlândia",
    "UFV - Universidade Federal de Viçosa",
    "UFVJM - Universidade Federal dos Vales do Jequitinhonha e Mucuri",
    "UNIFAL - Universidade Federal de Alfenas",
    "UNIFEI - Universidade Federal de Itajubá",
    "ESDHC - Escola Superior Dom Helder Câmara",
    "FACSFX - Faculdade São Francisco Xavier",
    "FADIPA - Faculdade de Direito de Ipatinga",
    "FAC - Faculdade Arquidiocesana de Curvelo",
    "FAP - Faculdade Arquidiocesana de Pirapora",
    "FAC FUNAM - Faculdade de Tecnologia Alto e Médio São Francisco",
    "FAZU - Faculdades Associadas de Uberaba",
    "FCMMG - Faculdade de Ciências Médicas de Minas Gerais",
    "FCMS/JF - Faculdade de Ciências Médicas e da Saúde de Juiz de Fora",
    "FMG - Faculdade Metodista Granbery",
    "FUNJOB - Faculdade de Medicina de Barbacena",
    "FUMEC - Fundação Mineira de Educação e Cultura",
    "INATEL - Instituto Nacional de Telecomunicações",
    "PUCMG - Pontifícia Universidade Católica de Minas Gerais",
    "UIT - Universidade de Itaúna",
    "UNIBH - Centro Universitário de Belo Horizonte",
    "UNILESTE - Centro Universitário Católica do Leste de Minas Gerais",
    "UNIPAC - Universidade Presidente Antônio Carlos",
    "UNIUBE - Universidade de Uberaba",
    "UNIVAS - Universidade do Vale do Sapucaí",
    "UNIVALE - Universidade Vale do Rio Doce",
    "UNINCOR - Universidade Vale do Rio Verde",
    "UNIVERSO - Universidade Salgado de Oliveira",
    "IMIH - Instituto Metodista Izabela Hendrix",
    "Unifenas - Universidade José do Rosário Vellano",
    "DOCTUM - Rede de Ensino Doctum",
    "FACIC - Faculdade de Ciências Humanas de Curvelo",
    "FACSUM - Faculdade do Sudeste Mineiro",
    "FACTU - Faculdade de Ciências e Tecnologia de Unaí",
    "FAF - Faculdade de Frutal",
    "FAJANSSEN - Faculdade Arnaldo Jessen",
    "FAVENORTE - Instituto Superior de Educação Verde Norte",
    "FMC - Faculdades Milton Campos",
    "FUC - Faculdades Unificadas de Cataguases",
    "IPTAN - Instituto de Ensino Superior Presidente Tancredo Neves",
    "UNA - Centro Universitário UNA",
    "UNEC - Centro Universitário de Caratinga",
    
    # Pará
    "UFRA - Universidade Federal Rural da Amazônia",
    "UFPA - Universidade Federal do Pará",
    "IFPA - Instituto Federal do Pará",
    "UFOPA - Universidade Federal do Oeste do Pará",
    "UNIFESSPA - Universidade Federal do Sul e Sudeste do Pará",
    "UEPA - Universidade do Estado do Pará",
    "CIABA - Centro de Instrução Almirante Braz de Aguiar",
    "CEAMA - Centro de Educação da Amazônia",
    "CESUPA - Centro Universitário do Estado do Pará",
    "ESMAC - Escola Superior Madre Celeste",
    "FAMAZ - Faculdade Metropolitana da Amazônia",
    "FABEL - Faculdade de Belém",
    "FACBEL - Faculdade Católica de Belém",
    "FACIP - Faculdade Ipiranga",
    "FAPAN - Faculdade Pan Amazônica",
    "FEAPA - Faculdade de Estudos Avançados do Pará",
    "FIBRA - Faculdade Integrada Brasil Amazônia",
    "UNAMA - Universidade da Amazônia",
    "UNIP - Universidade Paulista",
    
    # Paraíba
    "UEPB - Universidade Estadual da Paraíba",
    "IFPB - Instituto Federal da Paraíba",
    "UFPB - Universidade Federal da Paraíba",
    "UFCG - Universidade Federal de Campina Grande",
    "UNIPÊ - Centro Universitário de João Pessoa",
    "Uniuv - Centro Universitário de União da Vitória",
    "ESBJ - Faculdade Maurício de Nassau",
    "UNIBRASIL - Centro Universitário Autônomo do Brasil",
    "FAVAP - Faculdades Vale do Piancó",
    "IESP - Instituto de Educação Superior da Paraíba",
    "UNIFIP - Centro Universitário de Patos",
    "UNIFACISA - Centro Universitário Facisa",
    
    # Paraná
    "UNESPAR - Universidade Estadual do Paraná",
    "UEL - Universidade Estadual de Londrina",
    "UEM - Universidade Estadual de Maringá",
    "UENP - Universidade Estadual do Norte do Paraná",
    "UEPG - Universidade Estadual de Ponta Grossa",
    "UNICENTRO - Universidade Estadual do Centro-Oeste",
    "UNIOESTE - Universidade Estadual do Oeste do Paraná",
    "IFPR - Instituto Federal do Paraná",
    "UTFPR - Universidade Tecnológica Federal do Paraná",
    "UFPR - Universidade Federal do Paraná",
    "UNILA - Universidade Federal da Integração Latino-Americana",
    "UFFS - Universidade Federal da Fronteira Sul",
    "FAE - FAE Centro Universitário",
    "FAG - Fundação Assis Gurgacz",
    "FEPAR - Faculdade Evangélica do Paraná",
    "FTSA - Faculdade Teológica Sul Americana",
    "PUCPR - Pontifícia Universidade Católica do Paraná",
    "UNIFIL - Centro Universitário Filadélfia",
    "Univel - União Educacional de Cascavel",
    "UNINGÁ - Faculdade Ingá",
    "CAMPO REAL - Faculdade Campo Real",
    "CESCAGE - Centro de Ensino Superior dos Campos Gerais",
    "FAG - Faculdade Guairacá",
    "FAJAR - Faculdade Jaguariaíva",
    "FATEB - Faculdade de Telêmaco Borba",
    "FANP - Faculdade do Noroeste Paranaense",
    "FASBAM - Faculdade São Basílio Magno",
    "FEITEP - Faculdade de Engenharia e Inovação Técnico Profissional",
    "FG - Faculdade Guarapuava",
    "FML - Faculdade Metropolitana Londrinense",
    "UNICAMPO - Faculdade União de Campo Mourão",
    "INTEGRADO - Centro Universitário Integrado de Campo Mourão",
    "UniCesumar - Universidade Cesumar",
    "UNICURITIBA - Centro Universitário Curitiba",
    "UNINTER - Grupo Educacional Uninter",
    "UNIPAR - Universidade Paranaense",
    "UNOPAR - Universidade do Norte do Paraná",
    "UCP - Faculdades do Centro do Paraná",
    "UP - Universidade Positivo",
    "UTP - Universidade Tuiuti do Paraná",
    "UNISEP - União de Ensino do Sudoeste do Paraná",
    
    # Piauí
    "UFPI - Universidade Federal do Piauí",
    "IFPI - Instituto Federal do Piauí",
    "UFDPar - Universidade Federal do Delta do Parnaíba",
    "UESPI - Universidade Estadual do Piauí",
    "ICESPI - Instituto Católico de Estudos de Ensino Superior do Piauí",
    "UNINOVAFAPI - Centro Universitário Uninovafapi",
    "UNINASSAU - Centro Universitário Maurício de Nassau",
    
    # Rio de Janeiro
    "FeMASS - Faculdade Professor Miguel Ângelo da Silva Santos",
    "ISERJ - Instituto Superior de Educação do Rio de Janeiro",
    "FAETERJ - Faculdade de Educação Tecnológica do Estado do Rio de Janeiro",
    "UENF - Universidade Estadual do Norte Fluminense",
    "UERJ - Universidade do Estado do Rio de Janeiro",
    "UEZO - Universidade Estadual da Zona Oeste",
    "IMPA - Instituto de Matemática Pura e Aplicada",
    "CBPF - Centro Brasileiro de Pesquisas Físicas",
    "CEFET/RJ - Centro Federal de Educação Tecnológica Celso Suckow da Fonseca",
    "Colégio Pedro II",
    "ENCE - Escola Nacional de Ciências Estatísticas",
    "IFF - Instituto Federal Fluminense",
    "IFRJ - Instituto Federal do Rio de Janeiro",
    "UFF - Universidade Federal Fluminense",
    "UFRJ - Universidade Federal do Rio de Janeiro",
    "UFRRJ - Universidade Federal Rural do Rio de Janeiro",
    "UNIRIO - Universidade Federal do Estado do Rio de Janeiro",
    "ABMDP II - Academia de Bombeiro Militar Dom Pedro II",
    "AMAN - Academia Militar de Agulhas Negras",
    "APMDJ VI - Academia de Polícia Militar Dom João VI",
    "EN - Escola Naval",
    "ECEME - Escola de Comando e Estado-Maior do Exército",
    "EsAO - Escola de Aperfeiçoamento de Oficiais",
    "IME - Instituto Militar de Engenharia",
    "ESPM-RIO - Escola Superior de Propaganda e Marketing",
    "CELSO LISBOA - Centro Universitário Celso Lisboa",
    "FACHA - Faculdades Integradas Hélio Alonso",
    "FGV - Fundação Getulio Vargas",
    "FMC - Faculdade de Medicina de Campos",
    "FMP/FASE - Faculdade de Medicina de Petrópolis",
    "FSMA - Faculdade Salesiana de Macaé",
    "FSB/RJ - Faculdade de São Bento do Rio de Janeiro",
    "FUNENSEG - Escola Nacional de Seguros",
    "IBMEC - Instituto Brasileiro de Mercado e Capitais",
    "IBMR - Centro Universitário IBMR",
    "MACKENZIE-RIO - Faculdade Presbiteriana Mackenzie Rio",
    "PUC-RIO - Pontifícia Universidade Católica do Rio de Janeiro",
    "UCAM - Universidade Cândido Mendes",
    "UCB - Universidade Castelo Branco",
    "UCP - Universidade Católica de Petrópolis",
    "UGB - Centro Universitário Geraldo Di Biase",
    "UNIFAA - Centro de Ensino Superior de Valença",
    "UNISUAM - Centro Universitário Augusto Motta",
    "UNIABEU - UNIABEU Centro Universitário",
    "UNIFESO - Centro Universitário Serra dos Órgãos",
    "UNIGRANRIO - Universidade do Grande Rio",
    "UNIVERSO - Universidade Salgado de Oliveira",
    "USS - Universidade Severino Sombra",
    "USU - Universidade Santa Úrsula",
    "UVA - Universidade Veiga de Almeida",
    "AEDB - Faculdades Dom Bosco",
    "SENAC - Faculdade Senac Rio de Janeiro",
    "UBM - Centro Universitário de Barra Mansa",
    "UNESA - Universidade Estácio de Sá",
    "UNIFOA - Centro Universitário de Volta Redonda",
    
    # Rio Grande do Norte
    "UERN - Universidade do Estado do Rio Grande do Norte",
    "IFRN - Instituto Federal do Rio Grande do Norte",
    "UFERSA - Universidade Federal Rural do Semi-Árido",
    "UFRN - Universidade Federal do Rio Grande do Norte",
    "ULBRA - Universidade Luterana do Brasil (Polo Natal)",
    "UNP - Universidade Potiguar",
    "Fatern Gama Filho - Faculdade de Excelência do Rio Grande do Norte",
    "UNOPAR - Universidade Norte do Paraná (Polo Natal)",
    "UNINASSAU - Faculdade Maurício de Nassau",
    "IPOG - Instituto de Pós-Graduação",
    
    # Rondônia
    "UNIR - Universidade Federal de Rondônia",
    "IFRO - Instituto Federal de Rondônia",
    "FCR - Faculdade Católica de Rondônia",
    "UNIFSL - Centro Universitário São Lucas de Porto Velho",
    "UNIFSL - Centro Universitário São Lucas de Ji-paraná",
    "FAMA - Faculdade da Amazônia",
    
    # Roraima
    "UERR - Universidade Estadual de Roraima",
    "UFRR - Universidade Federal de Roraima",
    "IFRR - Instituto Federal de Roraima",
    "FARES - Faculdade Roraimense de Ensino Superior",
    
    # Santa Catarina
    "FURB - Fundação Universidade Regional de Blumenau",
    "SOCIESC - Sociedade Educacional de Santa Catarina",
    "UNESC - Universidade do Extremo Sul Catarinense",
    "FMP - Faculdade Municipal de Palhoça",
    "CEETEPS - Centro Estadual de Educação Tecnológica Paula Souza",
    "UDESC - Universidade do Estado de Santa Catarina",
    "UFFS - Universidade Federal da Fronteira Sul",
    "IFSC - Instituto Federal de Santa Catarina",
    "IFC - Instituto Federal Catarinense",
    "UFSC - Universidade Federal de Santa Catarina",
    "SENAC - Faculdade Senac - Santa Catarina",
    "UNOESC - Universidade do Oeste de Santa Catarina",
    "UNIASSELVI - Centro Universitário Leonardo da Vinci",
    "UNISUL - Universidade do Sul de Santa Catarina",
    "UNC - Universidade do Contestado",
    "UNIARP - Universidade Alto Vale do Rio do Peixe",
    "UNERJ - Centro Universitário de Jaraguá do Sul",
    "UNIVALI - Universidade do Vale do Itajaí",
    "UNIVILLE - Universidade da Região de Joinville",
    "UNOCHAPECÓ - Universidade Comunitária Regional de Chapecó",
    "UNIPLAC - Universidade do Planalto Catarinense",
    "UNISUL - Universidade do Sul de Santa Catarina",
    "Católica SC - Centro Universitário Católica de Santa Catarina",
    "UNIAVAN - Centro Universitário Avantis",
    "Cesusc - Complexo de Ensino Superior de Santa Catarina",
    
    # São Paulo
    "UNITAU - Universidade de Taubaté",
    "USCS - Universidade Municipal de São Caetano do Sul",
    "UNIFAE - Centro Universitário das Faculdades Associadas de Ensino",
    "Uni-FACEF - Centro Universitário de Franca",
    "CUFSA - Centro Universitário Fundação Santo André",
    "FACCAMP - Faculdade de Campo Limpo Paulista",
    "EEP/FUMEP - Escola de Engenharia de Piracicaba",
    "FDF - Faculdade de Direito de Franca",
    "FDSBC - Faculdade de Direito de São Bernardo do Campo",
    "FMABC - Faculdade de Medicina do ABC",
    "FMJ - Faculdade de Medicina de Jundiaí",
    "FAI - Faculdades Adamantinenses Integradas",
    "IMESA - Instituto Municipal de Ensino Superior de Assis",
    "FEA - Fundação Educacional Araçatuba",
    "USP - Universidade de São Paulo",
    "UNICAMP - Universidade Estadual de Campinas",
    "UNESP - Universidade Estadual Paulista",
    "UNIVESP - Universidade Virtual do Estado de São Paulo",
    "FAMEMA - Faculdade de Medicina de Marília",
    "FAMERP - Faculdade de Medicina de São José do Rio Preto",
    "FATEC - Faculdade de Tecnologia do Estado de São Paulo",
    "APMBB - Academia de Polícia Militar do Barro Branco",
    "UFSCar - Universidade Federal de São Carlos",
    "UNIFESP - Universidade Federal de São Paulo",
    "UFABC - Universidade Federal do ABC",
    "INPE - Instituto Nacional de Pesquisas Espaciais",
    "IFSP - Instituto Federal de Educação, Ciência e Tecnologia de São Paulo",
    "ITA - Instituto Tecnológico de Aeronáutica",
    "AFA - Academia da Força Aérea",
    "PUC-SP - Pontifícia Universidade Católica de São Paulo",
    "PUC-Campinas - Pontifícia Universidade Católica de Campinas",
    "UNIARA - Universidade de Araraquara",
    "UNISA - Universidade de Santo Amaro",
    "UNISANTOS - Universidade Católica de Santos",
    "UNIVAP - Universidade do Vale do Paraíba",
    "UNOESTE - Universidade do Oeste Paulista",
    "USF - Universidade São Francisco",
    "UNISANT'ANNA - Universidade Sant'Anna",
    "UMESP - Universidade Metodista de São Paulo",
    "UNAERP - Universidade de Ribeirão Preto",
    "MACK - Universidade Presbiteriana Mackenzie",
    "UNIMEP - Universidade Metodista de Piracicaba",
    "UNICASTELO - Universidade Camilo Castelo Branco",
    "UNISAGRADO - Universidade do Sagrado Coração",
    "UNISAL - Centro Universitário Salesiano de São Paulo",
    "UNICID - Universidade Cidade de São Paulo",
    "CUSC - Centro Universitário São Camilo",
    "FEBASP - Centro Universitário Belas Artes de São Paulo",
    "FEI - Centro Universitário FEI",
    "UNIFEV - Centro Universitário de Votuporanga",
    "FMU - Centro Universitário das Faculdades Metropolitanas Unidas",
    "SENAC - Centro Universitário Senac",
    "UNASP - Centro Universitário Adventista de São Paulo",
    "UNICEP - Centro Universitário Central Paulista",
    "UNIFAI - Centro Universitário Assunção",
    "UNIFEB - Centro Universitário da Fundação Educacional de Barretos",
    "UNIFEOB - Centro Universitário Octávio Bastos",
    "UNIFIEO - Centro Universitário FIEO",
    "UNILAGO - União das Faculdades dos Grandes Lagos",
    "UNIMONTE - Centro Universitário Monte Serrat",
    "UNIVEM - Centro Universitário Eurípedes de Marília",
    "ACCC - A.C.Camargo Cancer Center",
    "FCN - Faculdade Canção Nova",
    "BSP - Business School São Paulo",
    "FGV - Fundação Getúlio Vargas",
    "FECAP - Fundação Escola de Comércio Álvares Penteado",
    "ESPM - Escola Superior de Propaganda e Marketing",
    "ESAGS - Escola Superior de Administração e Gestão",
    "IMT - Instituto Mauá de Tecnologia",
    "FCL - Faculdade Cásper Líbero",
    "FAAP - Fundação Armando Álvares Penteado",
    "FACERES - Faculdade Ceres de Medicina",
    "Insper - Instituto de Ensino e Pesquisa",
    "IMT - Instituto Mauá de Tecnologia",
    "FESPSP - Fundação Escola de Sociologia e Política de São Paulo",
    "FRB - Faculdades Integradas Rio Branco",
    "FIO - Faculdades Integradas de Ourinhos",
    "FIRB - Faculdades Integradas Rio Branco",
    "FTML - Faculdade de Teologia Metodista Livre",
    "FAZP - Faculdade Zumbi dos Palmares",
    "FCMSCSP - Faculdade de Ciências Médicas da Santa Casa de São Paulo",
    "FDC - Fundação Dom Cabral",
    "FASM - Faculdade Santa Marcelina",
    "UNINOVE - Universidade Nove de Julho",
    "ICESP - Universidade Brasil",
    "ISES - Centro Universitário Sumaré",
    "ITE - Centro Universitário de Bauru",
    "UAM - Universidade Anhembi Morumbi",
    "UBC - Universidade Braz Cubas",
    "UMC - Universidade de Mogi das Cruzes",
    "UNG - Universidade Guarulhos",
    "UniABC - Universidade do Grande ABC",
    "UNIBAN - Universidade Bandeirante de São Paulo",
    "UNICSUL - Universidade Cruzeiro do Sul",
    "UNIFRAN - Universidade de Franca",
    "UNIMAR - Universidade de Marília",
    "UNINOVE - Universidade Nove de Julho",
    "UNIP - Universidade Paulista",
    "UNIMES - Universidade Metropolitana de Santos",
    "UNISANTA - Universidade Santa Cecília",
    "UNISO - Universidade de Sorocaba",
    "USJT - Universidade São Judas Tadeu",
    "UNITOLEDO - Centro Universitário Toledo",
    "FACAMP - Faculdades de Campinas",
    "FADI - Faculdade de Direito de Sorocaba",
    "FADISC - Faculdades Integradas de São Carlos",
    "FAM - Faculdade de Americana",
    "FIAP - Faculdade de Informática e Administração Paulista",
    "FADITU - Faculdade de Direito de Itu",
    "FIRB - Faculdades Integradas Rio Branco",
    "FIT - Faculdade Impacta Tecnologia",
    "FOC - Faculdades Oswaldo Cruz",
    "SLMANDIC - Faculdade de Odontologia e Centro de Pesquisas Odontológicas São Leopoldo Mandic",
    "ESEG - Escola Superior de Engenharia e Gestão",
    
    # Sergipe
    "UFS - Universidade Federal de Sergipe",
    "IFS - Instituto Federal de Sergipe",
    "Unit - Universidade Tiradentes",
    "FPD - Faculdade Pio Décimo",
    "ESTÁCIO - Faculdade Estácio de Sergipe",
    "FANESE - Faculdade de Administração e Negócios de Sergipe",
    "FAMA - Faculdade Amadeus",
    "FSLF - Faculdade São Luis de França",
    "UNOPAR - Universidade Norte do Paraná",
    "FASER - Faculdade Sergipana",
    "FACAR - Faculdade de Aracaju",
    "UNIRB - Faculdade Serigy",
    "FAJAR - Faculdade Jardins",
    "FA - Faculdade Atlântico",
    "UniCOC - Sistema COC de Educação"
]

import random
import pandas as pd

# Lista de cursos fornecida anteriormente
cursos = [
    "Administração", "Administração Pública", "Agroecologia", "Agronegócio", "Agronomia", 
    "Análise de Sistemas", "Antropologia", "Arquitetura e Urbanismo", "Arquivologia", "Artes", 
    "Artes Cênicas", "Astronomia", "Biblioteconomia", "Biologia", "Biomedicina", 
    "Bioquímica", "Canto", "Cenografia", "Ciência da Computação", "Ciências Biológicas", 
    "Ciências Contábeis", "Ciências Econômicas", "Ciências Sociais", "Cinema e Audiovisual", 
    "Composição e Regência", "Computação", "Comunicação e Marketing", "Comunicação Social", 
    "Desenho Industrial", "Design", "Design de Ambientes", "Design de Games", 
    "Design de Interiores", "Design de Moda", "Design de Produto", "Design Digital", 
    "Design Gráfico", "Direção", "Direito", "Educação Física", "Enfermagem", 
    "Engenharia Acústica", "Engenharia Aeroespacial", "Engenharia Aeronáutica", 
    "Engenharia Agrícola", "Engenharia Agroindustrial", "Engenharia Agronômica", 
    "Engenharia Ambiental", "Engenharia Automotiva", "Engenharia Bioenergética", 
    "Engenharia Biomédica", "Engenharia Bioquímica", "Engenharia Biotecnológica", 
    "Engenharia Cartográfica", "Engenharia Civil", "Engenharia da Computação", 
    "Engenharia da Mobilidade", "Engenharia de Agrimensura", "Engenharia de Agronegócios", 
    "Engenharia de Alimentos", "Engenharia de Aquicultura", "Engenharia de Automação", 
    "Engenharia de Bioprocessos", "Engenharia de Biossistemas", "Engenharia de Biotecnologia", 
    "Engenharia de Energia", "Engenharia de Gestão", "Engenharia de Informação", 
    "Engenharia de Instrumentação, Automação e Robótica", "Engenharia de Manufatura", 
    "Engenharia de Materiais", "Engenharia de Minas", "Engenharia de Pesca", 
    "Engenharia de Petróleo", "Engenharia de Produção", "Engenharia de Recursos Hídricos", 
    "Engenharia de Saúde e Segurança", "Engenharia de Sistemas", "Engenharia de Software", 
    "Engenharia de Telecomunicações", "Engenharia de Transporte e Logística", 
    "Engenharia Elétrica", "Engenharia Eletrônica", "Engenharia em Sistemas Digitais", 
    "Engenharia Ferroviária e Metroviária", "Engenharia Física", "Engenharia Florestal", 
    "Engenharia Geológica", "Engenharia Hídrica", "Engenharia Industrial", 
    "Engenharia Mecânica", "Engenharia Mecatrônica", "Engenharia Metalúrgica", 
    "Engenharia Naval", "Engenharia Química", "Engenharia Têxtil", "Estatística", 
    "Farmácia", "Filosofia", "Física", "Fisioterapia", "Fonoaudiologia", "Geografia", 
    "Gestão Ambiental", "Gestão da Informação", "Gestão de Políticas Públicas", 
    "Gestão de Serviços de Saúde", "Gestão do Agronegócio", "Gestão Pública", 
    "História", "Hotelaria", "Jornalismo", "Letras", "Marketing", "Matemática", 
    "Mecânica Industrial", "Medicina", "Medicina Veterinária", "Moda", "Música", 
    "Nutrição", "Odontologia", "Pedagogia", "Políticas Públicas", "Propaganda e Marketing", 
    "Psicologia", "Publicidade e Propaganda", "Química", "Rádio, TV e Internet", 
    "Relações Internacionais", "Relações Públicas", "Secretariado Executivo", 
    "Serviço Social", "Sistemas de Informação", "Tecnologias Digitais", "Teologia", 
    "Terapia Ocupacional", "Tradutor e Intérprete", "Turismo", "Zootecnia", 
]

# Opções de grau acadêmico e modalidades
graus_academicos = ["Bacharelado", "Licenciatura", "Tecnólogo"]
modalidades = ["Presencial", "EAD", "Semipresencial"]

# Função para gerar um código e-MEC aleatório
def gerar_codigo_emec():
    return random.randint(1000000, 9999999)

# Lista para armazenar os dados da tabela CURSO
dados_cursos = []

for curso in cursos:
    codigo_emec = gerar_codigo_emec()
    grau_academico = random.choice(graus_academicos)
    modalidade = random.choice(modalidades)
    dados_cursos.append([codigo_emec, curso, grau_academico, modalidade])

# Convertendo para DataFrame para visualização
df_cursos = pd.DataFrame(dados_cursos, columns=["codigoEMecCurso", "nome", "grauAcademico", "modalidade"])

# Exibindo os primeiros registros
print(df_cursos.head())

# Salvando em CSV para referência futura
df_cursos.to_csv("tabela_cursos.csv", index=False)


print(len(cursos))